[server]
maxUploadSize = 10000  # Sets limit to 10GB
enableCORS = false     # Helps mobile browsers connect more easily
enableXsrfProtection = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
